#!/bin/bash

if [ -f /usr/lib/openxt/ui-functions ]; then
    . /usr/lib/openxt/ui-functions
fi

UIM_PIDFILE="${UIM_PIDFILE:-/run/uim-toolbar-gtk.pid}"

if command -v "uim-toolbar-gtk3"; then
    UIM_TOOLBAR="uim-toolbar-gtk3"
elif command -v "uim-toolbar-gtk"; then
    UIM_TOOLBAR="uim-toolbar-gtk"
fi

if [ -z "${UIM_TOOLBAR}" ]; then
    echo "UIM (GTK) toolbar could not be found. Is uim-gtk3 or uim-gtk2 installed?" >&2
    exit 1
fi


# Usage: start_uim_toolbar
#   Start UIM toolbar, in configured environment, and reccord a pidfile for
#   process management.
start_uim_toolbar() {
    local pidfile="${UIM_PIDFILE}"
    local locale="$(xenmgr_get_locale)" 
    local show_toolbar="0"
    local enable_anthy="0"
    local enable_py="0"

    if [ -e "${pidfile}" ]; then
        if pgrep -F "${pidfile}" >/dev/null; then
            echo "${UIM_TOOLBAR} is already running." >&2
            return 1
        else
            echo "Spurious pidfile found for ${UIM_TOOLBAR}" >&2
            rm -f ${pidfile}
        fi
    fi

    local login_state="$(xenstore-read login/state 2>/dev/null)"
    local layout="$(xenstore-read /xenclient/keyboard/layout)"
    case "${login_state}" in
        "0"|"3"|"")
            case "${layout}" in
                "jp")   enable_anthy="1"
                        enable_toolbar="1"
                    ;;
                "cn")   enable_py="1"
                        enable_toolbar="1"
                    ;;
            esac
            ;;
    esac

    # XXX: Position should be configuration, currently display at the
    #      bottom-left corner.
    UIM_SHOW_TOOLBAR="${show_toolbar}" \
    UIM_ENABLE_ANTHY="${enable_anthy}" \
    UIM_ENABLE_PY="${enable_py}" \
    LANG="${locale}" \
        "${UIM_TOOLBAR}" +0-0 &
    echo $! > "${pidfile}"
}

# Usage: stop_uim_toolbar
stop_uim_toolbar() {
    local pidfile="${UIM_PIDFILE}"

    pkill -F "${pidfile}"
    rm -f "${pidfile}"
}

# Usage: monitor_uim_toolbar
#   Listen to XenMgr UI related signals.
monitor_uim_toolbar() {
    # Locale.
    local xgr_intf="com.citrix.xenclient.xenmgr"
    local xgr_lang_member="language_changed"
    local xgr_watch="$(dbus_watch_expression signal ${xgr_intf} ${xgr_lang_member})"

    # Monitor dbus watches, use "interface.member"
    while read type _ _ _ _ path intf member ; do
        case "${intf}.${member}" in
            "${xgr_intf}.${xgr_lang_member}")
                stop_uim_toolbar
                start_uim_toolbar
                ;;
            *) continue ;;
        esac
    done < <( dbus_watch "${xgr_watch}" )
}

## Start UIM toolbar.
start_uim_toolbar

## Monitor UIM toolbar.
monitor_uim_toolbar

## This should only happen when X stops.
stop_uim_toolbar
