#!/bin/sh
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

copy_dir ()
{
    local path="$1"
    mkdir -p "${OUT_DIR}/${path}"

    icbinn_ftp -d 0 -c "ls ${path}" | while read line  ; do
        case "${line}" in
             f*) file=${line#f }
                   copy_file "${path}/${file}"
                   ;;
             d*) dir=${line#d }
                 copy_dir "${path}/${dir}"
        esac
    done
}

copy_file ()
{
    local path="$1"
    icbinn_ftp -d 0 -c "get $path ${OUT_DIR}/${path}"
}

vm=`xenstore-read vm`
vm_uuid=${vm#/vm/}
CERTS_DIR="/var/lib/NetworkManager"

if [ "x${vm_uuid}" = "x" ]
then
    # dom0
    # FIXME: remove this section when removing NM from dom0
    exit 0
else
    if [ "${vm_uuid}" = "00000000-0000-0000-0000-000000000001" ]
    then 
        # uivm
        OUT_DIR=$CERTS_DIR
    else 
        # ndvm
        name=`xenstore-read name`
        [ "$?" -ne 0 ] && exit 0
        OUT_DIR="${CERTS_DIR}/${name}" 
    fi 
fi
echo $OUT_DIR

i=0
while [ "$i" -lt "5" ] ; do
     initialized=`icbinn_ftp -d 0 -c null`
     [ "$?" -eq 0 ] && break
     let "i += 1"
     sleep 2 
done
copy_dir "/"
