#!/bin/sh
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

DOMID=$1
STUBDOMID=$2

# configure and use per-vm alsa pcm device with softvol control
ALSA_VMID=$DOMID

# config files
ASOUND_CONF=/etc/asound.conf
ASOUND_CONF_VMID=/var/run/alsa-vm-${ALSA_VMID}.conf

# sound card
DB_PCM=`db-read /audio/playback-pcm`
if [ "$DB_PCM" != "" ]; then
    CARD=`echo $DB_PCM | cut -d '-' -f 1`
    CARD=$(( 10#$CARD ))
else
    CARD=0
fi

cat > ${ASOUND_CONF_VMID} <<END
pcm.vm-${ALSA_VMID} {
  type softvol
  slave {
    pcm "asym0"
  }
  control {
    name "vm-${ALSA_VMID}"
    card ${CARD}
  }
}
END
cat ${ASOUND_CONF} >> ${ASOUND_CONF_VMID}
export ALSA_CONFIG_PATH=/usr/share/alsa/alsa.conf:${ASOUND_CONF_VMID}
export QEMU_ALSA_DAC_DEV=plug:vm-${ALSA_VMID}
export QEMU_ALSA_VOL_CTRL=vm-${ALSA_VMID}

exec /usr/lib/xen/bin/audio_helper $STUBDOMID

