#!/bin/sh
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

DOMID=$1
shift 2

# configure and use per-vm alsa pcm device with softvol control
ALSA_VMID=$DOMID
cat >/var/run/alsa-vm-${ALSA_VMID}.conf <<END
pcm.vm-${ALSA_VMID} {
  type softvol
  slave {
    pcm "dmix"
  }
  control {
    name "vm-${ALSA_VMID}"
    card 0
  }
}
END
export ALSA_CONFIG_PATH=/usr/share/alsa/alsa.conf:/var/run/alsa-vm-${ALSA_VMID}.conf
export QEMU_ALSA_DAC_DEV=plug:vm-${ALSA_VMID}
export QEMU_ALSA_VOL_CTRL=vm-${ALSA_VMID}

name="qemu-$DOMID"

ARGS="$*"

# let's find the bsg devices if there are any.
{
    BSG_CDS=""

    # If cdrom-pt-ro was specified on the command line, use that instead of cdrom-pt
    if ! echo $ARGS | grep -vq cdrom-pt-ro; then
        CDROM_PT_ARG="-cdrom-pt-ro"
    else
        CDROM_PT_ARG="-cdrom-pt"
    fi

    for BSG in $(grep -B2 CD-ROM /proc/scsi/scsi | grep Host | sed -e 's/^.*scsi\([0-9]\+\).* \([0-9]\+\) .* \([0-9]\+\) .* \([0-9]\+\)/\1:\2:\3:\4/g' -e 's/0\([0-9]\)/\1/g') ; do
        BSG_DEVICE=/dev/bsg/$BSG
        if [ -c $BSG_DEVICE ]; then
            BSG_CDS="$BSG_CDS $CDROM_PT_ARG $BSG_DEVICE"
        fi
    done
    ARGS=`echo $ARGS | sed -e "s|$CDROM_PT_ARG XENCLIENT_CDROM_BSG|$BSG_CDS|;"`
} >/dev/null 2>&1

UUID=$(xec-vm -d $DOMID get uuid)
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/usb_proxy_socket /usr/bin/ctxusb argo ${DOMID} ${UUID} 0

logger -t $name "Using domid: $DOMID"
logger -t $name "Arguments: $ARGS"

export USE_INTEL_SB=1
export INTEL_DBUS=1
xenstore-write /local/domain/$DOMID/qemu-pid $$
exec /usr/lib/xen/bin/qemu-dm_alt -name qemu-$DOMID $ARGS
