Index: refpolicy/Makefile
===================================================================
--- refpolicy.orig/Makefile
+++ refpolicy/Makefile
@@ -46,6 +46,7 @@ endif
 # executable paths
 BINDIR ?= /usr/bin
 SBINDIR ?= /usr/sbin
+TC_SBINDIR ?= /sbin
 ifdef TEST_TOOLCHAIN
 tc_usrbindir := env LD_LIBRARY_PATH="$(TEST_TOOLCHAIN)/lib:$(TEST_TOOLCHAIN)/usr/lib" $(TEST_TOOLCHAIN)$(BINDIR)
 tc_usrsbindir := env LD_LIBRARY_PATH="$(TEST_TOOLCHAIN)/lib:$(TEST_TOOLCHAIN)/usr/lib" $(TEST_TOOLCHAIN)$(SBINDIR)
@@ -53,7 +54,7 @@ tc_sbindir := env LD_LIBRARY_PATH="$(TES
 else
 tc_usrbindir := $(BINDIR)
 tc_usrsbindir := $(SBINDIR)
-tc_sbindir := /sbin
+tc_sbindir := $(TC_SBINDIR)
 endif
 CHECKPOLICY ?= $(tc_usrbindir)/checkpolicy
 CHECKMODULE ?= $(tc_usrbindir)/checkmodule
