#! /bin/sh
#
# Copyright (c) 2010 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

xec -s com.citrix.xenclient.input -o / -i com.citrix.xenclient.input auth_rm_platform_user > /tmp/xec-output.$$
s=`cat /tmp/xec-output.$$ | head -n1`
e=`cat /tmp/xec-output.$$ | tail -n1`
rm -f /tmp/xec-output.$$
if [ "$s" = "false" ]; then
  echo "ERROR: $e"
  exit 1
fi

echo "Platform user removed."

exit 0
