(define custom-activate-default-im-name? #f)
(define custom-preserved-default-im-name 'direct)
(define default-im-name #f)
(define enabled-im-list '(py anthy))
(define enable-im-toggle? #t)
(define toggle-im-key '("<Meta> "))
(define toggle-im-key? (make-key-predicate '("<Meta> ")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-input-state-time-length 3)
