#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

while true ; do
   while true ; do
     backends=`DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 INET_IS_V4V=1 dbus-send --system --print-reply --dest=com.citrix.xenclient.networkdaemon / com.citrix.xenclient.networkdaemon.list_backends | grep string | awk '{print $2}'` ;
     [ "$?" -eq 0 ] && break
     sleep 0.1
   done

   for i in ${backends} ; do
     start-nm-applet ${i//\"/} &
   done
   wait
   sleep 2
done
