#!/bin/sh
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

echo $$ > /tmp/uim-toolbar-gtk.pid

UIM_SHOW_TOOLBAR=0
UIM_ENABLE_ANTHY=0
UIM_ENABLE_PY=0

LOGIN_STATE=$(xenstore-read "login/state" 2>/dev/null)

case "${LOGIN_STATE}" in "0"|"3"|"")
    KEYBOARD=$(xenstore-read /xenclient/keyboard/layout 2>/dev/null)
    LAYOUT=$(echo "${KEYBOARD}" | cut -d- -f1)

    case "${LAYOUT}" in
        jp)
            UIM_SHOW_TOOLBAR=1
            UIM_ENABLE_ANTHY=1
            ;;
        cn)
            UIM_SHOW_TOOLBAR=1
            UIM_ENABLE_PY=1
            ;;
    esac
esac

export UIM_SHOW_TOOLBAR
export UIM_ENABLE_ANTHY
export UIM_ENABLE_PY

LANG=$(get-language)
export LANG

exec /usr/bin/uim-toolbar-gtk "$@"
