#!/bin/sh
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# Keeps the uivm keyboard layout in sync with dom0.

KEYBOARD_LIST=/usr/share/xenclient/keyboards
XENSTORE_KEY=/xenclient/keyboard/layout
UIM_TOOLBAR_PID_FILE=/tmp/uim-toolbar-gtk.pid
OLD_KEYBOARD=

while true; do
    KEYBOARD=$(xenstore-read "${XENSTORE_KEY}" 2>/dev/null)

    if [ "${KEYBOARD}" -a "${KEYBOARD}" != "${OLD_KEYBOARD}" ] ; then
        LAYOUT=$(grep "^${KEYBOARD}:" "${KEYBOARD_LIST}" | cut -d: -f3)
        VARIANT=$(grep "^${KEYBOARD}:" "${KEYBOARD_LIST}" | cut -d: -f4)
        setxkbmap "${LAYOUT}" "${VARIANT}"

        if [ "${OLD_KEYBOARD}" ] ; then
            UIM_TOOLBAR_PID=$(cat "${UIM_TOOLBAR_PID_FILE}" 2>/dev/null)
            rm -f "${UIM_TOOLBAR_PID_FILE}"
            [ "${UIM_TOOLBAR_PID}" ] && kill "${UIM_TOOLBAR_PID}"
        fi

        OLD_KEYBOARD="${KEYBOARD}"
    fi

    sleep 1
done
