#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`

XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}

case "$1" in
online)
	xenstore-write "${XAPI}/vif" "${vif}"
	xenstore-write "${XAPI}/hotplug" "online"

        if [ ! -d "/storage/ndvm" ] ; then
            logger -s "backend_vif_notify bridge for  backend/${TYPE}/${DOMID}/${DEVID}: online"
            dbus-send --system --dest='com.citrix.xenclient.networkslave' --print-reply --reply-timeout=1000\
                      --type=method_call / com.citrix.xenclient.networkslave.backend_vif_notify \
                      string:"${vif}" uint32:${DOMID} uint32:${DEVID}
        fi
	;;
remove)
        logger -s "backend_vif_notify bridge for  backend/${TYPE}/${DOMID}/${DEVID}: remove"
	xenstore-rm "${XAPI}/hotplug"
	;;
esac
