#!/bin/sh

# pv driver
xenstore-write '/mh/XenSource-TM_XenEnterprise-TM' 'XenSource(TM) and XenEnterprise(TM) are registered trademarks of XenSource Inc.'
xenstore-chmod '/mh' r0
xenstore-chmod '/mh/XenSource-TM_XenEnterprise-TM' r0

if [ "`dmidecode -s system-manufacturer`" = "Hewlett-Packard"  ]
then
        # touchpad
        xenstore-write '/local/domain/0/hid_linux/touchpad-div' 8000
        xenstore-write '/local/domain/0/hid_linux/touchpad-limit' 500
fi

# touchpad
xenstore-write '/local/domain/0/hid_linux/touchpad-div' 8000
xenstore-write '/local/domain/0/hid_linux/touchpad-limit' 500

# blanker
xenstore-write '/local/domain/0/dom0_driver/blank' 2
xenstore-chmod '/local/domain/0/dom0_driver/blank' b0
xenstore-chmod '/local/domain/0/dom0_driver/natif' r0

xenstore-write '/local/domain/0/dom0_driver/command' ''
xenstore-chmod '/local/domain/0/dom0_driver/command' b0

xenstore-write '/xc_tools' ''
xenstore-chmod '/xc_tools' b0

