#! /bin/sh
#
# Copyright (c) 2010 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

CMD="$0"
usage()
{
        echo "$CMD: username"
}

if [ "$#" -ne 1 ] ; then
       usage
        exit 1
fi


exec 3>&2
#[ -z "$V" ] && exec >/dev/null 2>&1
exec >/tmp/sec-new-user.log 2>&1
err () { echo >&3 "$@"; }
quit () { logger -t sec-new-user < /tmp/sec-new-user.log; rm /tmp/sec-new-user.log; exit $1; }

user="`echo -n "$1" | openssl sha1`"

LVPREFIX=s-localuser-
LVNAME=${LVPREFIX}${user}

DIR="/config/users/${LVNAME}"
MOUNTPOINT="/config/sec/${LVNAME}"

echo "${DIR} ${MOUNTPOINT} auto defaults,bind 1 6" >> /etc/fstab

mkdir -p "${DIR}"
mkdir -p "${MOUNTPOINT}"
[ -x /sbin/restorecon ] && /sbin/restorecon -r "${DIR}" "${MOUNTPOINT}"

mount "${MOUNTPOINT}"

quit 0
