#!/bin/sh
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# Replaces the boot splash screens when the system language changes.

INTERFACE="com.citrix.xenclient.xenmgr"
MEMBER="language_changed"

XC_LANG=$(xec -g language)
/usr/share/xenclient/install-bootloader-images "${XC_LANG}"

dbus-monitor --system \
             --profile \
             "type='signal',interface='${INTERFACE}',member='${MEMBER}'" |
while read MESSAGE_TYPE X X X X MESSAGE_INTERFACE MESSAGE_MEMBER ; do
    if [ "${MESSAGE_TYPE}" = "sig" -a \
         "${MESSAGE_INTERFACE}" = "${INTERFACE}" -a \
         "${MESSAGE_MEMBER}" = "${MEMBER}" ] ; then

        XC_LANG=$(xec -g language)
        /usr/share/xenclient/install-bootloader-images "${XC_LANG}"

    fi
done
