--- squashfs-tools/Makefile	25 Aug 2010 18:19:12 -0000	1.51
+++ squashfs-tools/Makefile	29 Aug 2010 19:19:44 -0000
@@ -58,7 +58,7 @@
 UNSQUASHFS_OBJS = unsquashfs.o unsquash-1.o unsquash-2.o unsquash-3.o \
 	unsquash-4.o swap.o compressor.o gzip_wrapper.o
 
-CFLAGS = $(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
+CFLAGS_R = $(INCLUDEDIR) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
 	-D_GNU_SOURCE -DCOMP_DEFAULT=\"$(COMP_DEFAULT)\"  -O2 -Wall
 
 LIBS =
@@ -80,9 +80,9 @@
 
 ifdef XATTR_SUPPORT
 ifdef XATTR_DEFAULT
-CFLAGS += -DXATTR_SUPPORT -DXATTR_DEFAULT
+CFLAGS_R += -DXATTR_SUPPORT -DXATTR_DEFAULT
 else
-CFLAGS += -DXATTR_SUPPORT
+CFLAGS_R += -DXATTR_SUPPORT
 endif
 MKSQUASHFS_OBJS += xattr.o read_xattrs.o
 UNSQUASHFS_OBJS += read_xattrs.o unsquashfs_xattr.o
@@ -92,44 +92,61 @@
 all: mksquashfs unsquashfs
 
 mksquashfs: $(MKSQUASHFS_OBJS)
-	$(CC) $(MKSQUASHFS_OBJS) -lz -lpthread -lm $(LIBS) -o $@
+	$(CC) $(LDFLAGS) $(MKSQUASHFS_OBJS) -lz -lpthread -lm $(LIBS) -o $@
 
 mksquashfs.o: mksquashfs.c squashfs_fs.h mksquashfs.h global.h sort.h \
 	squashfs_swap.h xattr.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 read_fs.o: read_fs.c squashfs_fs.h read_fs.h global.h squashfs_swap.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 sort.o: sort.c squashfs_fs.h global.h sort.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 swap.o: swap.c
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 pseudo.o: pseudo.c pseudo.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 compressor.o: compressor.c compressor.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-xattr.o: xattr.h
+xattr.o: xattr.c xattr.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-read_xattrs.o: xattr.h
+read_xattrs.o: read_xattrs.c xattr.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
+
+gzip_wrapper.o: gzip_wrapper.c
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 unsquashfs: $(UNSQUASHFS_OBJS)
-	$(CC) $(UNSQUASHFS_OBJS) -lz -lpthread -lm $(LIBS) -o $@
+	$(CC) $(LDFLAGS) $(UNSQUASHFS_OBJS) -lz -lpthread -lm $(LIBS) -o $@
 
-unsquashfs.o: unsquashfs.h unsquashfs.c squashfs_fs.h squashfs_swap.h \
+unsquashfs.o:  unsquashfs.c unsquashfs.h squashfs_fs.h squashfs_swap.h \
 	squashfs_compat.h global.h xattr.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-unsquash-1.o: unsquashfs.h unsquash-1.c squashfs_fs.h squashfs_compat.h \
+unsquash-1.o: unsquash-1.c unsquashfs.h squashfs_fs.h squashfs_compat.h \
 	global.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-unsquash-2.o: unsquashfs.h unsquash-2.c unsquashfs.h squashfs_fs.h \
+unsquash-2.o: unsquash-2.c unsquashfs.h unsquashfs.h squashfs_fs.h \
 	squashfs_compat.h global.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-unsquash-3.o: unsquashfs.h unsquash-3.c squashfs_fs.h squashfs_compat.h \
+unsquash-3.o: unsquash-3.c unsquashfs.h squashfs_fs.h squashfs_compat.h \
 	global.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-unsquash-4.o: unsquashfs.h unsquash-4.c squashfs_fs.h squashfs_swap.h \
+unsquash-4.o: unsquash-4.c unsquashfs.h squashfs_fs.h squashfs_swap.h \
 	global.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
-unsquashfs_xattr.o: xattr.h
+unsquashfs_xattr.o: unsquashfs_xattr.c xattr.h
+	$(CC) $(CFLAGS_R) $(CFLAGS) -c -o $@ $<
 
 .PHONY: clean
 clean:
