#! /bin/sh

echo "Wireless AC $1"

WLANIF=`iwconfig 2> /dev/null | grep '^[a-z].' | cut -f1 -d" " | head -n1`
echo "Wireless interface is $WLANIF"

if [ "$1" = "1" ]; then
    echo "Turning wifi power saving off"
    iwconfig "$WLANIF" power off
else
    echo "Turning wifi power saving on"
    iwconfig "$WLANIF" power on
fi
