#!/bin/sh
#
# Copyright (c) 2008 Citrix Systems, Inc.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

# Writes to the store when this domain's frontend block device appears.
# Once this happens we should be safe opening the device.

# NB special handling of partition events:
# If we block-attach a device and then create partitions, events are
# generated with DEVPATHs of the form /block/xvde/xvde1 -- we ignore these
# If we block-attach a partition directly then events are generated
# with DEVPATHs of the form /block/xvde1 -- we act on these.

PARTITION=`echo ${DEVPATH} | cut -f 4 -d '/'`
if [ ! -z ${PARTITION} ]; then
        # the bad kind of partition
	exit
fi
 
DOMID=`xenstore-read domid`

# Extract the device type and ID from the PHYSDEVPATH eg
# PHYSDEVPATH=/devices/xen/vbd-51728
TYPE=`echo ${PHYSDEVPATH} | cut -f 4 -d '/' | cut -f 1 -d '-'`
DEVID=`echo ${PHYSDEVPATH} | cut -f 2 -d '-'`

XAPI=/xapi/${DOMID}/frontend/${TYPE}/${DEVID}

case "$1" in
add)
        xenstore-write "${XAPI}/hotplug" "online"
        ;;
remove)
        xenstore-rm "${XAPI}"
        ;;
esac
