#!/bin/sh
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

ROOT="${1}"
tmp_dir="$(mktemp -dt pcrs-XXXXX)/pcr-info"
PCRS_BAD_FILE="bad.pcrs"
PCRS_BAD_SRC="${ROOT}/storage/${PCRS_BAD_FILE}"
PCRS_BAD_DST="${tmp_dir}/${PCRS_BAD_FILE}"
PCRS_GOOD_FILE="good.pcrs"
PCRS_GOOD_SRC="${ROOT}/config/${PCRS_GOOD_FILE}"
PCRS_GOOD_DST="${tmp_dir}/${PCRS_GOOD_FILE}"
PCRS_DIFF="${tmp_dir}/pcrs.diff"
PCRS_STATE="${tmp_dir}/pcrs.log"

mkdir -p ${tmp_dir} > /dev/null
[ -f "${PCRS_GOOD_SRC}" ] && cp "${PCRS_GOOD_SRC}" "${PCRS_GOOD_DST}" > /dev/null
[ -f "${PCRS_BAD_SRC}" ]  && cp "${PCRS_BAD_SRC}" "${PCRS_BAD_DST}" > /dev/null
diff -u "${PCRS_GOOD_SRC}" "${PCRS_BAD_SRC}" > "${PCRS_DIFF}"
pcr-state "${ROOT}" > "${PCRS_STATE}"
pcr_state_ret=$?

echo "${tmp_dir}"
exit ${pcr_state_ret}
