#!/bin/sh
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

# attempt to start tcsd if it's not already running
# return 0 if tcsd is running or successfully started
#        1 otherwise
# A return status of 1 indicates the TPM driver is not loaded.
# In this state the TPM is disabled ... or the platform doesn't have one :)

clean_old_tpm_files () {
    [ -e /boot/system/tpm/config.tss ] && rm /boot/system/tpm/config.tss
    [ -e /boot/system/tpm/config.tss.pcrs ] && rm /boot/system/tpm/config.tss.pcrs
    [ -e /boot/system/tpm/config.tss.sha256 ] && rm /boot/system/tpm/config.tss.sha256
    [ -e /boot/system/tpm/config.tss.pub.sha256 ] && rm /boot/system/tpm/config.tss.pub.sha256
}

# Usage: get_tpm_version [DEVID]
# Print the version of the TPM device with DEVID (default to 0).
get_tpm_version() {
    local devid="${1:-0}"
    local path="$(tpm_get_syspath "${devid}")"

    # See the TPM chardev driver implementation:
    # https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/drivers/char/tpm/tpm-sysfs.c?h=v4.14.34#n296
    # Assuming a TPM has already been detected, absence of the sysfs entry
    # means TPM 2.0.
    # This is still valid on Linux 4.16.
    if [ ! -e "${path}/device/caps" ]; then
        echo "2.0"
    else
        awk '/TCG version:/ { print $3 }' "${path}/device/caps"
    fi
}

is_tpm_2_0 () {
    [ "$(get_tpm_version)" = "2.0" ]
}

# Usage: pcr_bank_exists HASH-ALGORITHM-STRING
# Returns successfuly if a matching bank exists for the given hash algorithm.
pcr_bank_exists () {
    local alg_in="$1"
    local bank
    local banks=$(tpm2_pcrread | cut -d ':' -f 1 | grep -i "sha")

    for bank in $banks; do
        if [ "${bank}" = "${alg_in}" ]; then
            return 0
        fi
    done
    return 1
}

# For comparison, normalize to 0x-prefixed, lowercase, unpadded, hex values
# e.g. 0x000B -> 0xb
tpm2_normalize() {
    printf "%#x" $1
}

OXT_HANDLE_SHA256=0x81000000
# SHA1 currently unused
OXT_HANDLE_SHA1=0x81000001
OXT_HANDLES="${OXT_HANDLE_SHA256}"
OXT_HANDLES_COUNT="$( echo "${OXT_HANDLES}" | wc -w )"

# TPM2 Object attribute bits
TPMA_OBJECT_FIXEDTPM=0x00000002
TPMA_OBJECT_FIXEDPARENT=0x00000010
TPMA_OBJECT_ADMINWITHPOLICY=0x00000080
TPMA_OBJECT_NODA=0x00000400
OXT_SEAL_ATTR=$( tpm2_normalize $(( TPMA_OBJECT_FIXEDTPM | \
                                    TPMA_OBJECT_FIXEDPARENT | \
                                    TPMA_OBJECT_ADMINWITHPOLICY | \
                                    TPMA_OBJECT_NODA )) )

# TPM2 hash algorithms
TPM_ALG_SHA1=0x4
TPM_ALG_SHA256=0xb
TPM_ALG_SHA384=0xc
TPM_ALG_SHA512=0xd
TPM_ALG_SM3_256=0x12

# TPM2 encryption algorithms
TPM_ALG_RSA=0x1
TPM_ALG_KEYEDHASH=0x8
TPM_ALG_ECC=0x23
TPM_ALG_SYMCIPHER=0x25

handle_type() {
    case "$1" in
        ${OXT_HANDLE_SHA256}) echo "rsa" ;;
        ${OXT_HANDLE_SHA1})   echo "rsa" ;;
        *)                    echo "INVALID_TYPE" ;;
    esac
}

handle_alg() {
    case "$1" in
        ${OXT_HANDLE_SHA256}) echo "sha256" ;;
        ${OXT_HANDLE_SHA1})   echo "sha1" ;;
        *)                    echo "INVALID_ALG" ;;
    esac
}

# Usage: alg_to_handle TPM-ALGORITHM-CODE
# Print the matching handle code for the given TPM algorithm code, or nothing
# if no match is found.
# Supported: OXT_HANDLE_SHA1, OXT_HANDLE_SHA256.
alg_to_handle () {
    local alg="$1"

    case "${alg}" in
        "${TPM_ALG_SHA1}") echo "${OXT_HANDLE_SHA1}" ;;
        "${TPM_ALG_SHA256}") echo "${OXT_HANDLE_SHA256}" ;;
    esac
}

# Usage: hashalg_to_alg HASH-ALGORITHM-STRING
# Print the matching TPM algorithm code for the given hash algorithm, or
# nothing if no match is found.
# Supported: sha1, sha256, sha384, sha512, sm3_256.
hashalg_to_alg() {
    local hashalg="$1"

    case "${hashalg}" in
        "sha1") echo "${TPM_ALG_SHA1}" ;;
        "sha256") echo "${TPM_ALG_SHA256}" ;;
        "sha384") echo "${TPM_ALG_SHA384}" ;;
        "sha512") echo "${TPM_ALG_SHA512}" ;;
        "sm3_256") echo "${TPM_ALG_SM3_256}" ;;
    esac
}

tcsd_running() {
    if [ ! -x "/etc/init.d/trousers" ]; then
        return 1
    fi
    /etc/init.d/trousers status > /dev/null 2>&1
}

tcsd_start() {
    # TPM2.0 TSS does not require tcsd.
    if is_tpm_2_0; then
        return 0
    fi
    if tcsd_running; then
        return 0
    fi

    /etc/init.d/trousers start
}
# Function to determin whether or not the TPM is active
# returns 0 if active
#         1 if inactive
#         2 if indeterminant
tpm_is_active() {
    local tpm="$(find /sys/class -name tpm0 2>/dev/null)/device"
    local active
    local msg
    local val

    if is_tpm_2_0 ; then
        msg=$(tpm2_getcap properties-variable 2>&1) || \
            return 2

        # Ensure Hierarchies are enabled; otherwise the TPM2 is unusable.
        for v in phEnable shEnable ehEnable phEnableNV; do
            val="$( echo "${msg}" | awk "/${v}:/ { print \$2 }" )"
            [ "${val}" = "1" ] || return 1
        done

        return 0
    fi

    active="$(cat ${tpm}/active)" || return 2

    if [ "${active}" -eq 1 ]; then
        return 0
    fi

    return 1
}
# Function to determine whether or not the TPM is enabled
# return 0 if TPM is enabled
#        1 if TPM is disabled
#        2 if indeterminant
tpm_is_enabled() {
    local tpm="$(find /sys/class -name tpm0 2>/dev/null)/device"
    local state=""

    if is_tpm_2_0 ; then
        tpm2_getcap properties-fixed 1>/dev/null 2>&1
        return $?
    else
        state=$(cat ${tpm}/enabled)
        if [ $? -ne 0 ]; then
            return 2
        fi
    fi

    [ $state -eq 1 ] && state=0 || state=1

    return $state
}

# Function to determine if a single tpm2 handle is correct
# returns 0 if the handle is defined
#         1 if the handle is not defined
#         2 if the handle is incorrect
tpm2_handle_defined() {
    local oxt_handle="$1"
    local handles=$(tpm2_getcap handles-persistent)
    local handle_str=$(echo "${handles}" | grep -w "${oxt_handle}")
    if [ -z "${handle_str}" ]; then
            return 1
    fi

    # Get handle value
    local handle=$( echo "${handle_str}" | cut -d ' ' -f 2)

    # Parse handle alg and type
    local alg=$( echo "${handle}" | grep -A1 '^name-alg:' | grep 'value:' | awk '{print $2}')
    local h_type=$( echo "${handle}" | grep -A1 '^type:' | grep 'value:' | awk '{print $2}')

    if [ "${h_type}" != "$( handle_type "${oxt_handle}" )" -o \
            "${alg}" != "$( handle_alg "${oxt_handle}" )" ]; then
        return 2
    fi

    return 0
}

# Function to determine if we have all the correct tpm2 handles
# returns 0 if the handles are defined
#         1 if the handles are not defined
#         2 if the handles are incorrect
tpm2_handles_defined() {
    local num_handles=$( tpm2_getcap handles-persistent | wc -l )

    if [ "${num_handles}" -eq 0 ]; then
        return 1
    fi

    if [ "${num_handles}" -ne ${OXT_HANDLES_COUNT} ]; then
        return 2
    fi

    local handle
    for handle in ${OXT_HANDLES}; do
        tpm2_handle_defined ${handle} || return $?
    done

    return 0
}

# Function to determine if we have the correct tpm handles
# returns 0 if the handles are defined
#         1 if the handles are not defined
#         2 if the handles are incorrect
tpm_handles_defined() {
    #Return success for TPM1
    is_tpm_2_0 || return 0

    tpm2_handles_defined
}

tpm2_clear_handle() {
    local passwd="$(cat "$1")"
    local handle="$2"

    tpm2_evictcontrol -C o -c "${handle}" -P "${passwd}"
}

# Clear out all the TPM handles.  This should help avoid issues with a TPM2's
# limited number of handles.
tpm_clear_handles() {
    local passwd="$1"
    local handles
    local handle

    is_tpm_2_0 || return 0

    # Expected output format: "- <handle>"
    # Extract just the handle
    handles=$( tpm2_getcap handles-persistent | cut -d ' ' -f 2 )
    for handle in ${handles} ; do
        tpm2_clear_handle "${passwd}" "${handle}"
    done
}

# Creates TPM2 handles.  Already existing handles are cleared before
# recreating.
tpm_create_handles() {
    local passwd="$1"
    local ret

    is_tpm_2_0 || return 0

    tpm2_handles_defined
    case $? in
        0) return 0;;
        1) ;; # not defined
        2) tpm_clear_handles "${passwd}" ;;
        *) echo "tpm_create_handle: handles in unexpected state!" 1>&2
           return 1
           ;;
    esac

    tpm2_create_handle "${passwd}"
}

# Function to determine whether or not the TPM is owned.
# returns 0 if TPM is owned
#         1 if TPM is not owned
#         2 if indeterminant
tpm_is_owned() {
    local tpm="$(find /sys/class -name tpm0 2>/dev/null)/device"
    local state="0"

    is_tpm_2_0
    local tpm2=$?
    if [ "${tpm2}" -eq 0 ];
    then
        tpm2_getcap properties-variable | grep -q 'ownerAuthSet:[[:space:]]*1'
        ret=$?
        if [ "${ret}" -eq 0 ]; then
            state=1
        fi
    else
        state=$(cat ${tpm}/owned)
        if [ $? -ne 0 ]; then
            return 2
        fi
    fi

    [ $state -eq 1 ] && state=0 || state=1

    return $state
}
# Function to determin whether or not the TPM owner password is the well known
#   secret of 20 bytes of 0's
# returns 0 if owner password is WKS
#         1 if owner password is not WKS
#         2 if indeterminant
#         3 if TPM is in an authentication time-out period
tpm_is_owner_wks() {
    local ret=0
    local msg=""

    is_tpm_2_0
    local tpm2=$?
    if [ "${tpm2}" -eq 0 ];
    then
        return $ret
    fi

    msg=$(tpm_setenable -z -s 2>&1)
    if [ $? -ne 0 ]; then
        case "$msg" in
            *TPM\ is\ deactivated) ret=2 ;;
            *TPM\ is\ disabled) ret=2 ;;
            *Authentication\ failed) ret=1 ;;
            *is\ in\ some\ time-out\ period) ret=3 ;;
            *No\ SRK) ret=1 ;;
            *) ret=2 ;;
        esac
    fi
    return $ret
}

tpm2_check_password() {
    local passwd="$1"
    local msg

    # Validate owner password by setting
    err=$(tpm2_changeauth -c owner "${passwd}" -p "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set owner auth: ${err}" >&2
        return ${ret}
    fi

    # Validate endorsement password by setting
    err=$(tpm2_changeauth -c endorsement "${passwd}" -p "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set endorsement auth: ${err}" >&2
        return ${ret}
    fi

    # Validate lockout password by setting
    err=$(tpm2_changeauth -c lockout "${passwd}" -p "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set lockout auth: ${err}" >&2
        return ${ret}
    fi
    return 0
}

# Function to determine if we have the TPM owner password
# returns 0 if owner password is ${passwd}'s contents
#         1 if owner password is not in ${passwd}
#         2 if indeterminant
#         3 if TPM is in an authentication time-out period
tpm_check_owner_password() {
    local passwd="$1"
    local ret=0
    local msg=""

    is_tpm_2_0
    local tpm2=$?
    if [ "${tpm2}" -eq 0 ];
    then
        tpm2_check_password "${passwd}"
        return $?
    fi

    msg=$(cat "${passwd}" | tpm_setenable --stdin -s 2>&1)
    if [ $? -ne 0 ]; then
        case "$msg" in
            *Authentication\ failed) ret=1 ;;
            *is\ in\ some\ time-out\ period) ret=3 ;;
            *) ret=2 ;;
        esac
    fi
    return $ret
}
# Function to determine whether or not the TPM SRK pasword is the well known
#   20 bytes of 0's.
# returns 0 if TPM SRK passwd is WKS
#         1 if TPM SRK passwd is not WKS
#         2 if indeterminant
#         3 if TPM is in an authentication time-out period
tpm_is_srk_wks() {
    local ret=0
    local msg=""

    is_tpm_2_0
    local tpm2=$?
    if [ "${tpm2}" -eq 0 ];
    then
        return $ret
    fi

    msg=$(echo "data" | tpm_sealdata -z 2>&1)
    if [ $? -ne 0 ]; then
        case "$msg" in
            *TPM\ is\ deactivated) ret=2 ;;
            *TPM\ is\ disabled) ret=2 ;;
            *Authentication\ failed) ret=1 ;;
            *is\ in\ some\ time-out\ period) ret=3 ;;
            *No\ SRK) ret=1 ;;
            *No\ EK) ret=1 ;;
            *) ret=2 ;;
        esac
    fi
    return $ret
}
# Function to determine whether or not the TPM has an EK
# NOTE: 99.99% of the platforms in this world ship with an EK from the factory.
#       The only systems I've seen w/o EKs have been Intell branded boards.
# returns 0 if TPM has an EK
#         1 if TPM does not have an EK
#         2 if indeterminant
#         3 if TPM is in an authentication time-out period
tpm_has_ek() {
    local ret=0
    local msg=""

    #tpm2.0 most likely has EK. TODO: figure out if I need to verify this.
    is_tpm_2_0
    local tpm2=$?
    if [ "${tpm2}" -eq 0 ];
    then
        ret=0
    else
        msg=$(echo "data" | tpm_sealdata -z 2>&1)
        if [ $? -ne 0 ]; then
            case "$msg" in
                *TPM\ is\ deactivated) ret=2 ;;
                *TPM\ is\ disabled) ret=2 ;;
                *No\ SRK | *Authentication\ failed | *Handle\ is\ incorrect) ;;
                *is\ in\ some\ time-out\ period) ret=3 ;;
                *No\ EK)  ret=1 ;;
                *) ret=2 ;;
            esac
        fi
    fi
    return $ret
}

#Taking ownership for tpm2 is slightly more complicated. Encapsulate this process
#in its own function, checking err after each critical operation.
tpm2_ownership () {
    local passwd=$(cat "$1")
    # Set owner password
    err=$(tpm2_changeauth -c owner "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set owner auth: ${err}" >&2
        return ${ret}
    fi

    # Set endorsement password
    err=$(tpm2_changeauth -c endorsement "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set endorsement auth: ${err}" >&2
        return ${ret}
    fi

    # Set lockout password
    err=$(tpm2_changeauth -c lockout "${passwd}" 2>&1)
    ret=$?
    if [ ${ret} -ne 0 ]; then
        echo "Failed to set lockout auth: ${err}" >&2
        return ${ret}
    fi
    tpm_clear_handles "${passwd}"
    tpm2_create_handle "$1"
}

tpm2_create_handle() {
    local passwd=$(cat "$1")

    # Create our primary object for SHA256 alg
    local type="$( handle_type "${OXT_HANDLE_SHA256}" )"
    local alg="$( handle_alg "${OXT_HANDLE_SHA256}" )"
    local h_ctx="/tmp/handle.ctx"
    
    handle=$(tpm2_createprimary -C o -c ${h_ctx} -g ${alg} -G ${type} -P "${passwd}")

    if [ $? -ne 0 ] || [ ! -f ${h_ctx}]; then
        echo "Failed to create primary"
        return 1
    fi

    #Make it permanent for this measured install
    err=$(tpm2_evictcontrol -C o -c ${h_ctx} -P "${passwd}" \
          $(alg_to_handle "${TPM_ALG_SHA256}") 2>&1)
    ret=$?
    rm -f ${h_ctx}

    if [ $ret -ne 0 ]; then
        echo "${err}"
        return ${ret}
    fi

    return 0
}

# Function to take ownership of the TPM.  Wraps some common functionality to
#   create an EK and check that we can seal with the well-known SRK.
# parameter 0: password
#           1: create EK (true|false)
# return 0 on success
#        1 on error
tpm_take_ownership() {
    local passwd="$1"
    local has_ek="${2:-false}"

    is_tpm_2_0
    local tpm2=$?

    # create EK if necessary
    case ${has_ek} in
        true) ;;
        false)
            err=$(tpm_createek 2>&1)
            if [ $? -ne 0 ]; then
                echo "error creating EK for TPM: ${err}" >&2
                return 1
            fi
            ;;
        *)
            echo "invalid parameter for EK: ${has_ek}" >&2
            return 1
    esac

    if [ "${tpm2}" -eq 0 ];
    then
        err=$(tpm2_ownership ${passwd})
    else
        # take ownership of TPM
        err=$(tpm_takeownership --srk-well-known --stdin 2>&1 < "${passwd}")
    fi

    if [ $? -ne 0 ]; then
        echo "error taking ownership of TPM: ${err}" >&2
        return 1
    fi

    #sealing data with wks is tpm 1.2 only
    if [ "${tpm2}" -eq 1 ];
    then
        # check to be sure we can seal data with the well-known-key
        err=$(echo data | tpm_sealdata -z 2>&1 >/dev/null)
        [ $? -ne 0 ] && {
            echo "Test to seal data with well-known SRK failed with error: ${err}" >&2
            return 1
        }
    fi
    return 0
}

# Write a tboot policy to a TPM2 NV index
# will only write if necessary
# $1 - New tboot policy file
# $2 - NV index
# $3 - TPM password
# Standard 0 success return value
tpm2_write_tboot_policy() {
    local policy="$1"
    # remove leading 0s from hex index to match tpm2_nvlist output
    local tboot_idx="$( tpm2_normalize $2 )"
    local password="$3"
    local old_policy="${policy}.old"
    local polsize=$(cat "${policy}" | wc -c)

    # To limit scope, these TPM2 globals values are defined locally
    # TPM2 permanent handles
    local TPM_RH_OWNER=0x40000001
    # TPM2 NVRAM attributes
    local TPMA_NV_TPMA_NV_WRITTEN=0x20000000
    local TPMA_NV_TPMA_NV_OWNERWRITE=0x00000002
    local TPMA_NV_TPMA_NV_AUTHWRITE=0x00000004
    local TPMA_NV_TPMA_NV_OWNERREAD=0x00020000
    local TPMA_NV_TPMA_NV_AUTHREAD=0x00040000
    local TBOOT_NV_ATTRIB="$( tpm2_normalize $(( TPMA_NV_TPMA_NV_OWNERWRITE | \
                                                 TPMA_NV_TPMA_NV_AUTHWRITE  | \
                                                 TPMA_NV_TPMA_NV_OWNERREAD  | \
                                                 TPMA_NV_TPMA_NV_AUTHREAD )) )"

    # Check if index exis
    if tpm2_getcap handles-nv-index | grep -q "${tboot_idx}"; then
        local idx=$(tpm2_nvreadpublic ${tboot_idx})
        local attr=$( echo "${idx}" | \
                  sed -n "/attributes:/,/value:/p" | \
                  awk -F: '/value:/ { print $2 }' | \
                  tr -d ' ' )
        local size=$( echo "${idx}" | \
                  awk -F: '/size:/ { print $2 }' | \
                  tr -d ' ' )

        # Read the current contents into a temp file.
        # tpm2_nvread could fail, and this ends up being a big pipeline to
        # create an empty file, but that is fine for below.
        tpm2_nvread "${tboot_idx}" -C "${TPM_RH_OWNER}" -P "${password}" \
            -s "${size}" -o "${old_policy}" >/dev/null 2>&1 || true

        if cmp -s "${old_policy}" "${policy}"; then
            rm -f "${old_policy}"
        return 0
        fi
        rm -f "${old_policy}"

        # If size or attributes mismatch, undefine
    if [ "${size}" != "${polsize}" ] || \
           [ "$( tpm2_normalize $(( attr & ~TPMA_NV_TPMA_NV_WRITTEN )) )" != "${TBOOT_NV_ATTRIB}" ]; then
            tpm2_nvundefine "${tboot_idx}" -C "${TPM_RH_OWNER}" \
                -P "${password}" >/dev/null 2>&1 || true
        fi
    fi

    # Define the index
    tpm2_nvdefine "${tboot_idx}" \
        -C "${TPM_RH_OWNER}" \
        -P "${password}" \
        -s "${polsize}" \
        -a "${TBOOT_NV_ATTRIB}" >/dev/null 2>&1 || return 1

    # Write the policy
    tpm2_nvwrite "${tboot_idx}" \
        -C "${TPM_RH_OWNER}" \
        -P "${password}" \
        -i "${policy}" >/dev/null 2>&1
}

# Usage: tpm_get_syspath [TPM-DEVICE-ID]
# Verify and print the path of the TPM, with the given id (default:0), on
# stdout. Returns 0 on success, 1 if the path in the sysfs cannot be found.
tpm_get_syspath() {
    local devid="${1:-0}"
    local syspath="/sys/class/tpm/tpm${devid}"

    if [ ! -e "${syspath}" ]; then
        echo "tpm_get_syspath: tpm${devid} has no entry in the sysfs." >&2
        return 1
    fi
    echo "${syspath}"
}

# Usage: tpm_get_ev_separator
# Print the EV_SEPARATOR value as presented by the kernel, or our best guess as
# what it may be, on stdout.
tpm_get_ev_separator() {
    local evs

    if is_tpm_2_0; then
        # TPM 2.0: `printf "\xff\xff\xff\xff" | sha256sum`, best guess...
        evs="df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119"
    else
        # TPM 1.2 will expose a securityfs node with ASCII values.
        local path="/sys/kernel/security/tpm0/ascii_bios_measurements"

        evs=$(awk '$1 == 4 && $3 == 04 { print $2 }' "${path}")
        # Fallback: Pick `printf "\xff\xff\xff\xff" | sha1sum`, best guess...
        evs=${evs:-"d9be6524a5f5047db5866813acf3277892a7a30a"}
    fi
    echo "${evs}"
}

# Usage: tpm_list_pcrs
# Print all the PCR values of the first TPM on stdout.
tpm_list_pcrs() {
    if is_tpm_2_0; then
        tpm2_pcrread
    else
        cat "$(tpm_get_syspath)/device/pcrs"
    fi
}

# tpm_pcrlist_save PCRLIST-FILE PCR-IDS
# Write the list of PCR-IDS to the PCRLIST-FILE, overwriting the existing one
# if necessary.
tpm_pcrlist_save() {
    local file="$1"
    shift 1
    local pcrlist=""

    # Sanity check list of number in PCR id range ([0-23])
    for p in "$@"; do
        pcrid="${p%%:*}"
        if [ "$(expr "${pcrid}" : '^[[:digit:]]\+$')" -a \
             "${pcrid}" -gt 23 -o "${pcrid}" -lt 0 ]; then
            return 1
        fi
        pcrlist="${pcrlist} ${pcrid}"
    done

    echo "${pcrlist}" > "${file}"
}

# tpm_pcrs_to_opts PCR-IDS
# Print a list of options from PCR-IDS suitable to use as argument with TSS
# utilities. This makes handling TPM1.2 and TPM2.0 TSS stacks easier.
tpm_pcrs_to_opts() {
    local tss_opt
    local pcr_opts

    if is_tpm_2_0; then
        tss_opt="-r"
    else
        tss_opt="-p"
    fi
    for p in "$@"; do
        pcr_opts="${pcr_opts} ${tss_opt} ${p}"
    done
    echo "${pcr_opts}"
}

# Usage: tpm_pcr_value_normalize PCR-VALUE
# Print the PCR-VALUE, from TPM-TSS output, normalized on stdout.
# Normalized here means no space, all lowercase, no PCR identifier, and only
# the last line.
# This is relevant for to be consistent across TSS versions and keeps format
# sanitizing in one centralized place, should it require to be amended.
tpm_pcr_value_normalize() {
    echo "$1" | awk -F ':' 'END{ gsub(" ", "", $2); print tolower($2) }'
}

# Usage: tpm_get_hash_algorithm
# Print the default hash algorithm to use within the current environment.
tpm_get_hash_algorithm() {
    local hashalg="sha1"

    if is_tpm_2_0; then
        if pcr_bank_exists "sha256"; then
            hashalg="sha256"
        fi
    fi
    echo "${hashalg}"
}

# Usage: tpm_get_pcr PCR-ID
# Print the content of PCR-ID on stdout. The value is normalized: all
# lowercase, no space.
tpm_get_pcr() {
    local pcr="$1"
    local hashalg="$(tpm_get_hash_algorithm)"

    if is_tpm_2_0; then
        tpm_pcr_value_normalize "$(tpm2_pcrread ${hashalg}:${pcr})"
    else
        tpm_pcr_value_normalize "$(grep "$(printf "PCR-%02d" "$pcr")" "$(tpm_get_syspath)/device/pcrs")"
    fi
}

# Usage tpm_save_keyfiles BASENAME
# Rename the existing sealed key files for BASENAME with the .old suffix.
tpm_save_keyfiles() {
    local basename="$1"
    local ext

    for ext in {,.pub}.sha1 {,.pub}.sha256; do
        if [ -e "${basename}${ext}" ]; then
            mv "${basename}${ext}" "${basename}${ext}.old"
        fi
    done
}

# Usage tpm_restore_keyfiles BASENAME
# Renamed the saved key files for BASENAME without the .old suffix.
# Fails if the saved key files are incoherent.
tpm_restore_keyfiles() {
    local basename="$1"
    local valid="false"
    local ext alg

    if is_tpm_2_0; then
        for alg in sha1 sha256; do
            if [ -e "${basename}.${alg}.old" -a -e "${basename}.pub.${alg}.old" ]; then
                valid="true"
            fi
        done
    else
        if [ -e "${basename}.sha1.old" ]; then
            valid="true"
        fi
    fi
    if [ "${valid}" != "true" ]; then
        return 1
    fi

    for ext in {,.pub}.sha1 {,.pub}.sha256; do
        if [ -e "${basename}${ext}.old" ]; then
            mv "${basename}${ext}.old" "${basename}${ext}"
        fi
    done
}

# Usage: tpm_seal [ -a hash-algorithm ] [-r path-to-root ] [ -p pcr-id[:value] ] SECRET-KEY-FILE TSS-BASENAME
# Seal the secret key file and create the sealed key/key-pair for unsealing.
# Existing key(s) will be saved and renamed with the .old suffix on success.
tpm_seal() {
    local root=""
    local hashalg="$(tpm_get_hash_algorithm)"
    local pcrs=""
    local OPTIND
    local opt
    local allout

    while getopts ":a:r:p:" opt; do
        case "${opt}" in
            a) hashalg="${OPTARG}" ;;
            r) root="${OPTARG}" ;;
            p) pcrs="${pcrs} ${OPTARG}" ;;
        esac
    done
    shift $((OPTIND-1))

    local secret="${root}/$1"
    local tss="${root}/$2"

    if ! tpm_pcrlist_save "${tss}.pcrs" ${pcrs}; then
        echo "tpm_seal: Failed to save PCR ID list." >&2
        return 1
    fi

    if is_tpm_2_0; then
        # Get comma separated list of PCR banks for use in tpm2 utilities
        local pcrs_arg="$(echo "${pcrs}" | xargs | tr ' ' ',')"
        local alg="$(hashalg_to_alg "${hashalg}")"
        local handle="$(alg_to_handle "${alg}")"

        if [ -z "${alg}" -o -z "${handle}" ] || \
            ! pcr_bank_exists "${hashalg}"; then
            echo "tpm_unseal: Algorithm \"${hashalg}\" is not supported." >&2
            return 1
        fi

        tpm_save_keyfiles "${tss}"

        # Create PCR-bound policy
        local policy_file="${tss}.policy.dat"
        local session_ctx="${tss}.session.ctx"

        tpm2_startauthsession -S "${session_ctx}" > /dev/null
        if [ $? -ne 0 ]; then
            echo "tpm_seal: Failed to start policy session" >&2
            tpm_restore_keyfiles "${tss}"
            return 1
        fi

        tpm2_policypcr -S "${session_ctx}" -l "${hashalg}:${pcrs_arg}" -L "${policy_file}" > /dev/null
        if [ $? -ne 0 ]; then
            echo "tpm_seal: Failed to bind PCRs to policy" >&2
            tpm2_flushcontext "${session_ctx}" > /dev/null
            tpm_restore_keyfiles "${tss}"
            return 1
        fi

        tpm2_flushcontext "${session_ctx}" > /dev/null

        # Seal the data using the policy
        local out_priv="${tss}.priv.${hashalg}"
        local out_pub="${tss}.pub.${hashalg}"

        allout="$(tpm2_create -C "${handle}" -i "${secret}" -u "${out_pub}" -r "${out_priv}" -L "${policy_file}" 2>&1)"
        if [ $? -ne 0 ]; then
            echo "tpm_seal: Failed to seal data (TPM 2.0):" >&2
            echo "${allout}" >&2
            tpm_restore_keyfiles "${tss}"
            return 1
        fi
    else
        local tss_bin="tpm_sealdata"
        if ! tcsd_running; then
            tss_bin="${tss_bin}_sa"
        fi
        tpm_save_keyfiles "${tss}"
        allout="$(${tss_bin} -i "${secret}" -o "${tss}.sha1" -z $(tpm_pcrs_to_opts ${pcrs}) 2>&1)"
        if [ $? -ne 0 ]; then
            echo "tpm_seal: Failed to seal data (TPM 1.2):" >&2
            echo "${allout}" >&2
            tpm_restore_keyfiles "${tss}"
            return 1
        fi
    fi

    return 0
}

# Usage: tpm_unseal [ -a hash-algorithm ] [-r path-to-root ] TSS-FILE-BASENAME
# Ask the TPM for the secret key using the sealed TSS keys given the current
# PCR values.
# Print the secret on stdout on success, otherwise print the error logs on
# stderr and nothing on stdout.
tpm_unseal() {
    local root=""
    local hashalg="$(tpm_get_hash_algorithm)"
    local pcrs=""
    local OPTIND
    local opt
    # Capture stderr into this variable while stdout is output normally.
    # The usual sleight of hand goes:
    #    { stderr="$(cmd args 2>&1 1>&3 3>&-)"; } 3>&1
    local stderr

    while getopts ":a:r:" opt; do
        case "${opt}" in
            a) hashalg="${OPTARG}" ;;
            r) root="${OPTARG}" ;;
        esac
    done
    shift $((OPTIND-1))

    local tss="${root}/$1"

    if is_tpm_2_0; then
        # Get comma separated list of PCR banks for use in tpm2 utilities
        local pcrs="$(echo $(cat "${tss}.pcrs"))"
        local pcrs_arg="$(echo "${pcrs}" | xargs | tr ' ' ',')"
        local alg="$(hashalg_to_alg "${hashalg}")"
        local handle="$(alg_to_handle "${alg}")"

        if [ -z "${alg}" ] || ! pcr_bank_exists "${hashalg}"; then
            echo "tpm_unseal: Algorithm \"${hashalg}\" is not supported." >&2
            return 1
        fi
    
        # Load the sealed object
        local obj_ctx="${tss}.sealed.ctx"
        local session_ctx="${tss}.session.ctx"
        tpm2_load -C "${handle}" -u "${tss}.pub.${hashalg}" -r "${tss}.priv.${hashalg}" -c "${obj_ctx}" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "tpm_unseal: Failed to load sealed object" >&2
            return 1
        fi

        # Unseal
        tpm2_startauthsession --policy-session -S "${tss}.session.ctx"
        tpm2_policypcr -S "${session_ctx}" -l "${hashalg}:${pcrs_arg}" -L "${tss}.policy.dat" > /dev/null
        { stderr="$(tpm2_unseal -psession:${session_ctx} -c "${obj_ctx}" 2>&1 1>&3 3>&-)"; } 3>&1
        if [ $? -ne 0 ]; then
            echo "tpm_unseal: Failed to unseal data (TPM 2.0) using ${hashalg} algorithm, ${stderr}" >&2
            return 1
        fi
    else
        local tss_bin="tpm_unsealdata"

        # Use the standalone binary if tcsd is not running.
        if ! tcsd_running; then
            tss_bin="${tss_bin}_sa"
        fi
        # tpm_unsealdata_sa does not offer to unseal against a given list of
        # PCRs.
        { stderr="$(${tss_bin} -z -i "${tss}.sha1" 2>&1 1>&3 3>&-)"; } 3>&1
        if [ "$?" -ne 0 ]; then
            echo "tpm_unseal: Failed to unseal data (TPM 1.2): " >&2
            echo "${stderr}" >&2
            return 1
        fi
    fi

    return 0
}

QUIRK_D="/usr/lib/tpm-scripts/quirks.d"

[ -d "${QUIRK_D}" ] || {
    echo "no quirk.d directory: ${QUIRK_D}, fail" >&2
    exit 1
}

# run *-detect.sh scripts from QUIRK_D directory
# execute callbacks based on quirk script exit status
# return status
#   0 : either no quirks or only quirks with workarounds
#   1 : platform has fatal quirks (quirks with no workarounds)
#       or caller has chosen to make non-fatal quirks fatal
#   2 : error condition: unexpected value returned from quirk detect script
#   3 : missing / bad parameter
quirk_detect () {
    local fptr_info="$1"
    local fptr_fatal="$2"
    local msg=""
    local ret=0

    [ -z ${fptr_info} ] && {
        echo "No quirk \"info\" callback provided."
        return 3
    }
    [ -z ${fptr_fatal} ] && {
        echo "No quirk \"fatal\" callback provided."
        return 3
    }

    for detect in $(ls -1 "${QUIRK_D}"/*-detect.sh); do
        msg=$(${detect} 2>&1)
        case $? in
            # no quirk
            0)  ;;
            # quirk: work around exists, call 'info' function
            # exit if 'info' function returns anything but 0
            #   this is a way for calling script to reject quirk work around
            1)  ${fptr_info} "${msg}"
                ret=$?
                [ ${ret} -ne 0 ] && return "${ret}"
                ;;
            # quirk: no work around
            2)  ${fptr_fatal} "${msg}"
                ret=$?
                [ ${ret} -eq 0 ] && return 1
                echo "ignoring fatal quirk, this is a bad idea ..."
                ;;
            # error condition, bad quirk script
            *)  echo "unexpected return value from quirk detect script: ${detect}" >&2
                return 2
                ;;
        esac
    done
    return 0
}

# run *-fix.sh scripts from QUIRK_D directory
# return status
#   0 : all fixes successful
#   1 : fix script returned non-zero status, error message is sent to stderr
#   2 : internal error
quirk_fix () {
    local root="${1:-/}"
    local ignore_errs="${2:-false}"
    local detect=""
    local fix=""
    local quirk_name=""
    local msg=""

    [ -d "${root}" ] || {
        echo "quirk_fix root param is not a directory: ${root}" >&2
        return 2
    }

    for fix in $(ls -1 "${QUIRK_D}"/*-fix.sh); do
        # run detect script
        quirk_name=$(echo "${fix}" | sed -e "s&${QUIRK_D}/\(.*\)-fix.sh&\1&")
        detect="${QUIRK_D}/${quirk_name}-detect.sh"
        [ -x "${detect}" ] || {
            echo "Quirk ${quirk_name} has no detect script, abort." >&2
            return 0
        }
        msg=$(${detect} 2>&1)
        case $? in
            0)  break ;; # quirk doesn't apply, break
            1)  ;;       # quirk does apply, NOOP
            2)  echo "Quirk deetct script ${detect} reports quirk is fatal but a fix script exists.  Not applying fix.  Consult quirk documentation."
                break
                ;;
            *)  echo "Error code returned from quirk detect script: ${detect}."
                break
                ;;
        esac
        # run fix script
        msg=$(${fix} "${root}" 2>&1)
        case $? in
            0)  ;;
            *)  [ "${ignore_errs}" != "true" ] && {
                    echo "Error returned by ML Quirk fix script: ${fix}.  Error message: ${msg}" >&2
                    return 1
                }
                ;;
        esac
    done
}
