BLKTAP_PATCHQUEUE = " \
    file://blktap-resume-fix.patch \
    file://blktap2-miscellaneous-oxt-fixes.patch \
    file://blktap2-libvhd-atomic-write-helpers.patch \
    file://blktap2-vhd-marker-flag.patch \
    file://blktap2-vhd-print-allocated-virtblock-list.patch \
    file://blktap2-tap-ctl-optional-pid-ro-mount.patch \
    file://blktap2-vhd-keyhash-support.patch \
    file://blktap2-vhd-encryption-support.patch \
    file://blktap2-vhd-icbinn-support.patch \
    file://blktap2-libxl-crypto-key-dir.patch \
"
