#!/bin/sh
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`

XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}

case "$1" in
    online)
        if [ "x${vif}" = "x" ]; then
            exit
        fi
        xenstore-write "${XAPI}/vif" "${vif}"
        xenstore-write "${XAPI}/hotplug" "online"

        iptables -N INPUT_${vif}
        iptables -N FORWARD_${vif}
        iptables -A INPUT_vifs -m physdev --physdev-in ${vif} -j INPUT_${vif}
        iptables -A FORWARD_vifs -m physdev --physdev-in ${vif} -j FORWARD_${vif}

        #bridge
        BRIDGE=`xenstore-read backend/${TYPE}/${DOMID}/${DEVID}/bridge`
        if [ -z $BRIDGE ]; then
            BRIDGE=brbridged
        fi
        if [ ! -d /proc/sys/net/ipv4/conf/$BRIDGE ]; then
            brctl addbr $BRIDGE
        fi
        brctl addif $BRIDGE ${vif}
        ifconfig ${vif} inet 0.0.0.0 promisc up
        #end bridge
        ;;
    remove)
        xenstore-rm "${XAPI}/hotplug"

        iptables -D INPUT_vifs -m physdev --physdev-in ${vif} -j INPUT_${vif}
        iptables -D FORWARD_vifs -m physdev --physdev-in ${vif} -j FORWARD_${vif}
        iptables -F INPUT_${vif}
        iptables -F FORWARD_${vif}
        iptables -X INPUT_${vif}
        iptables -X FORWARD_${vif}
        ;;
esac

