#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# Fetches the system language and outputs the equivalent locale name.

REPLY=$(DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 \
        LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 \
        INET_IS_V4V=1 \
        dbus-send --system \
                  --dest=com.citrix.xenclient.xenmgr \
                  --print-reply \
                  / \
                  org.freedesktop.DBus.Properties.Get \
                  string:com.citrix.xenclient.xenmgr.config.ui \
                  string:language) || exit 1

XC_LANG=$(echo "${REPLY}" | \
          sed -n 's/^ *variant *string *"\([^"]*\)".*$/\1/p')

LANGUAGE=$(echo "${XC_LANG}" | cut -d- -f1)
TERRITORY=$(echo "${XC_LANG}" | cut -d- -f2 | tr a-z A-Z)
CHARSET="UTF-8"

echo "${LANGUAGE}_${TERRITORY}.${CHARSET}"
