#!/bin/sh

# Kick udev to launch any necessary argo-input-sender processes
start() {
    udevadm trigger -c add -t devices -s input
}

case "$1" in
    start)
        start
        ;;
    *)
        echo "Command '$1' not supported"
        exit 1
        ;;
esac
