#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#
# Restarts the network manager applet, UIM toolbar and GNOME keyring daemon
# when the system language changes.

INTERFACE="com.citrix.xenclient.networkdomain.notify"
MEMBER="backend_state_changed"
UIM_TOOLBAR_PID_FILE="/tmp/uim-toolbar-gtk.pid"
GNOME_KEYRING_DAEMON_NAME="gnome-keyring-daemon.real"

DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 \
    INET_IS_V4V=1 \
    LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 \
    dbus-monitor --system \
                 --profile \
                 "type='signal',interface='${INTERFACE}',member='${MEMBER}'" |
while read MESSAGE_TYPE X X X X MESSAGE_INTERFACE MESSAGE_MEMBER ; do
    if [ "${MESSAGE_TYPE}" = "sig" -a \
         "${MESSAGE_INTERFACE}" = "${INTERFACE}" -a \
         "${MESSAGE_MEMBER}" = "${MEMBER}" ] ; then
 
        # restart all nm-applets
        for pid_file in `ls /tmp/start-nma*.pid /tmp/nm-applet*.pid` ; do
            pid=`cat "${pid_file}"` 
            [ "${pid}" ] && kill "${pid}"
            rm -f "${pid_file}"
        done

        UIM_TOOLBAR_PID=$(cat "${UIM_TOOLBAR_PID_FILE}" 2>/dev/null)
        rm -f "${UIM_TOOLBAR_PID_FILE}"
        [ "${UIM_TOOLBAR_PID}" ] && kill "${UIM_TOOLBAR_PID}"

        killall gnome-keyring-daemon.real

    fi
done
done
