#!/bin/sh
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

obj=$1
uuid=`DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 INET_IS_V4V=1 dbus-send --system --print-reply --dest=com.citrix.xenclient.networkdaemon $obj  org.freedesktop.DBus.Properties.Get string:"com.citrix.xenclient.networkdomain.config" string:"uuid" | grep string |  awk '{ print $3 }'`;

domid=`DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 INET_IS_V4V=1 dbus-send --system --print-reply --dest=com.citrix.xenclient.networkdaemon $obj  org.freedesktop.DBus.Properties.Get string:"com.citrix.xenclient.networkdomain.config" string:"domid" | grep uint32 |  awk '{ print $3 }'`;

name=`DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.0,port=5555 LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 INET_IS_V4V=1 dbus-send --system --print-reply --dest=com.citrix.xenclient.networkdaemon $obj  org.freedesktop.DBus.Properties.Get string:"com.citrix.xenclient.networkdomain.config" string:"name" | sed -n 's/^ *variant *string *"\(.*\)"$/\1/p'`

if [ "x${uuid}" = "x"  -o "x${domid}" = "x" -o "x${name}" = "x" ] ; then 
    exit 0 ;
fi

DEFAULT_CERTS_DIR="/var/lib/NetworkManager/$name"
export DEFAULT_CERTS_DIR

echo $$ > /tmp/start-nma-${uuid//\"/}.pid
while true ; do
     INET_IS_V4V=1 LD_PRELOAD=/usr/lib/libv4v-1.0.so.0 DBUS_SYSTEM_BUS_ADDRESS=tcp:host=1.0.0.$domid,port=5555 nm-applet-wrapper $uuid 
     sleep 2 
done
