#!/bin/sh
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Installs the XenClient bootloader images for the specified language.
#
# Usage: install-bootloader-images [language]
#
# If no language is specified, uses the language that was specified on the
# previous invocation. Failing that, uses the default language of "en-us".

DEFAULT_LANGUAGE="en-us"
SAVED_LANGUAGE_FILE="/boot/system/config/grub-language.conf"
IMAGES_DIR="/usr/share/xenclient/bootloader/images"

if [ $# -eq 0 ]; then
    LANGUAGE=
elif [ $# -eq 1 ] ; then
    LANGUAGE="$1"
else
    echo "Usage: install-bootloader-images [language]"
    exit 1
fi

if [ -z "$LANGUAGE" -a -r "$SAVED_LANGUAGE_FILE" ] ; then
    LANGUAGE=$(cat "$SAVED_LANGUAGE_FILE")
fi

if [ -z "$LANGUAGE" ] ; then
    echo "Using default language '$DEFAULT_LANGUAGE'." >&2
    LANGUAGE="$DEFAULT_LANGUAGE"
elif [ ! -d "$IMAGES_DIR/$LANGUAGE" ] ; then
    echo "Language '$LANGUAGE' not available; using '$DEFAULT_LANGUAGE'." >&2
    LANGUAGE="$DEFAULT_LANGUAGE"
fi

rm -f "$SAVED_LANGUAGE_FILE"
echo "$LANGUAGE" > "$SAVED_LANGUAGE_FILE"
restorecon "$SAVED_LANGUAGE_FILE"

cp -f "$IMAGES_DIR/"black.png "$IMAGES_DIR/$LANGUAGE/"booting.png /boot/system/grub

ln -sfn $IMAGES_DIR/$LANGUAGE /config/boot-images
restorecon /config/boot-images

