#!/bin/sh
# Copyright (C) 2018 Apertus Solutions, LLC
# Licensed on MIT

lvm_enabled() {
    if command -v lvm >/dev/null 2>&1; then
        return 0
    else
        debug "lvm doesn't exist"
        return 1
    fi
}

lvm_run() {
    info "Configuring LVM"
    lvm vgchange -a y
    lvm vgscan --mknodes
}
