#!/bin/bash

config=${1:-"/dev/xenclient/config"}

if [ ! -e "${config}" ]; then
	echo "Unable to locate config volume: ${config}"
	exit 1
fi

slot7=$(cryptsetup luksDump "${config}"|grep 'Slot 7'|awk '{ print $4 }')

case $slot7 in
ENABLED)
	echo "System is using legacy recovery key scheme"
;;
DISABLED)
	echo "System is using new recovery key scheme"
;;
*)
	echo "Unable to determine recovery key scheme"
;;
esac
