#! /bin/bash

dir="$(dirname "$0")"
name="$(basename "$0")"
if [ ! -e "${dir}/block-common.sh" ]; then
    logger -p "daemon.err" -t "${name}" -- \
        "Failed to find xen hotplug script framework in \"${dir}\"."
    exit 1
fi

. "${dir}/block-common.sh"

case "${command}" in
    "add")
        success
        ;;
    *)
        ;;
esac
