#! /bin/sh -e
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

test -x /usr/sbin/acpid || exit 0
test -d /proc/acpi || exit 0

case "$1" in
  start)
    echo -n "Starting Advanced Configuration and Power Interface daemon: "
    start-stop-daemon -S -x /usr/sbin/acpid -- -c /etc/acpi/events
    /etc/acpi/ac
    echo "acpid."
    ;;
  stop)
    echo -n "Stopping Advanced Configuration and Power Interface daemon: "
    start-stop-daemon -K -x /usr/sbin/acpid
    echo "acpid."
    ;;
  restart|force-reload) 
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/acpid {start|stop|restart|force-reload}"
    exit 1
esac

exit 0
