#!/bin/sh
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

echo 'config qemu network with xen bridge for ' $*

# we ignore the bridge passed to the script and set an identity mapping:
# tapX.0 <-> stubdombr0 <-> eth0
# ...
# tapX.n <-> stubdombrn <-> ethn
#
# maybe it's not the best place to handle this, but it looks simpler and
# nicer than handling it on toolstack level

ifnumber=${1##*.}

# xl adds "-emu" at the end, we need to remove that too
ifnumber=${ifnumber%-emu}

bridgename="stubdombr${ifnumber}"

if [ -e "/sys/class/net/${bridgename}" ];then
    echo "Bridge $bridgename already exists, strange (invoked for $1)"
else
    echo "creating bridge $bridgename"
    brctl addbr "$bridgename"
    # Forward 802.1d link-local packets like 802.1x.
    echo 0xfff8 > /sys/class/net/"$bridgename"/bridge/group_fwd_mask
    # Disable STP to avoid setup delays
    brctl stp "$bridgename" off
    brctl setfd "$bridgename" 0
fi

#Query xenstore for mac address of vif and match with mac found in
#sys/class/net
domid=$(xenstore-read domid)
xenstore_mac=$(xenstore-read /local/domain/${domid}/device/vif/${ifnumber}/mac)

for netif in $(ls /sys/class/net/); do
    if [ "${xenstore_mac}" == "$(cat /sys/class/net/${netif}/address)" ]; then
        ethname="${netif}"
        break
    fi
done

if [ -z ${ethname} ]; then
    echo "For mac address: ${xenstore_mac} from interface: ${1} from xenstore, could not match with any known network interface."
    exit 1
fi

if [ ! -e "/sys/class/net/$ethname" ]; then
    echo "$ethname does not exist, strange (invoked for $1)"
else
    echo "Adding $ethname and $1 to $bridgename"
    brctl addif $bridgename $ethname
    ifconfig $ethname 0.0.0.0
    brctl addif $bridgename $1
    ifconfig $1 0.0.0.0
    ifconfig $bridgename up
fi
